using InvoiceManagementApi.Models;
using InvoiceManagementApi.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;

namespace InvoiceManagementApi.Controllers
{
    [Route("api/[controller]/[Action]")]
    [ApiController]
    [Authorize]
    public class DCController : BaseController
    {
        private readonly ILogger<DCController> _logger;
        private readonly IDCRepository _dcRepository;

        public DCController(ILogger<DCController> logger, IDCRepository dcRepository)
        {
            _logger = logger;
            _dcRepository = dcRepository;
        }

        [HttpGet]
        public async Task<IActionResult> GetDCList([FromQuery] string? dcNum = null, [FromQuery] string? fromDate = null, [FromQuery] string? toDate = null)
        {
            try
            {
                var data = await _dcRepository.GetDCAsync(dcNum, fromDate, toDate, CurrentUserId);

                // Project the dynamic objects to properly parse the SQL JSON string into an actual JSON object
                var formattedData = data.Select(row =>
                {
                    // Dapper dynamic rows act like a dictionary
                    var rowDict = (IDictionary<string, object>)row;

                    // Extract the raw JSON string generated by SQL's FOR JSON PATH
                    string? jsonDetails = rowDict.ContainsKey("JsonDCDetails")
                        ? rowDict["JsonDCDetails"]?.ToString()
                        : null;

                    // Parse it back to an object/element so ASP.NET serializes it properly instead of escaping quotes
                    rowDict["JsonDCDetails"] = !string.IsNullOrEmpty(jsonDetails)
                        ? JsonSerializer.Deserialize<JsonElement>(jsonDetails)
                        : null;

                    return rowDict;
                });

                return Ok(formattedData);
            }
            catch (System.Exception ex)
            {
                _logger.LogError(ex, "Error getting DC List");
                return StatusCode(500, new { Message = "An error occurred" });
            }
        }

        /// <summary>
        /// Accepts an Invoice payload, performs basic validation and computes line/totals.
        /// Persists invoice via IInvoiceRepository.
        /// </summary>
        [HttpPost]
        public async Task<IActionResult> AddDC([FromBody] DCModel dc)
        {
            if (dc == null)
                return BadRequest(new { Message = "DC is required." });

            if (dc.Items == null || !dc.Items.Any())
                return BadRequest(new { Message = "DC must contain at least one item." });

            try
            {
                // Compute per-item amounts and invoice totals.
                decimal subTotal = 0m;
                decimal totalCgst = 0m;
                decimal totalSgst = 0m;
                decimal totalIgst = 0m;

                foreach (var item in dc.Items)
                {
                    // Basic sanitization
                    item.Quantity = Math.Max(0m, item.Quantity);
                    item.Rate = Math.Max(0m, item.Rate);
                    item.DiscountPercentage = Math.Clamp(item.DiscountPercentage, 0m, 100m);

                    // Gross amount (before discount)
                    var gross = Decimal.Round(item.Rate * item.Quantity, 2);

                    // Discount amount
                    var discountAmount = Decimal.Round(gross * (item.DiscountPercentage / 100m), 2);

                    // Taxable value (after discount)
                    var taxable = Decimal.Round(gross - discountAmount, 2);

                    // Determine tax percentages to apply for this item:
                    var cgstPer = dc.CgstPer ?? 0m;
                    var sgstPer = dc.SgstPer ?? 0m;
                    var igstPer = dc.IgstPer ?? 0m;

                    // If invoice-level percentages are not provided, assume item.Cgst/Sgst/Igst hold monetary tax values already.
                    decimal cgstAmount = cgstPer > 0m ? Decimal.Round(taxable * (cgstPer / 100m), 2) : item.Cgst;
                    decimal sgstAmount = sgstPer > 0m ? Decimal.Round(taxable * (sgstPer / 100m), 2) : item.Sgst;
                    decimal igstAmount = igstPer > 0m ? Decimal.Round(taxable * (igstPer / 100m), 2) : item.Igst;

                    // Total line amount
                    var lineTotal = Decimal.Round(taxable + cgstAmount + sgstAmount + igstAmount, 2);

                    // Populate item computed fields (respecting provided shape)
                    item.Amount = gross;
                    item.TaxableValue = taxable;
                    item.Cgst = cgstAmount;
                    item.Sgst = sgstAmount;
                    item.Igst = igstAmount;
                    item.Total = lineTotal;

                    subTotal += taxable;
                    totalCgst += cgstAmount;
                    totalSgst += sgstAmount;
                    totalIgst += igstAmount;
                }

                dc.SubTotal = Decimal.Round(subTotal, 2);
                dc.TotalCgst = Decimal.Round(totalCgst, 2);
                dc.TotalSgst = Decimal.Round(totalSgst, 2);
                dc.TotalIgst = Decimal.Round(totalIgst, 2);
                dc.GrandTotal = Decimal.Round(dc.SubTotal + dc.TotalCgst + dc.TotalSgst + dc.TotalIgst, 2);

                // Persist invoice using repository
                var repoResult = await _dcRepository.InsertOrUpdateDCAsync(dc, CurrentUserId);

                _logger.LogInformation("Invoice {InvoiceId} saved by user {UserId}. SubTotal={SubTotal}, GrandTotal={GrandTotal}",
                    dc.Id, CurrentUserId?.ToString() ?? "anonymous", dc.SubTotal, dc.GrandTotal);

                return Ok(new
                {
                    Message = "Invoice processed and saved successfully.",
                    Invoice = dc,
                    Result = repoResult
                });
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error processing invoice");
                return StatusCode(500, new { Message = "An error occurred while processing the invoice." });
            }
        }
    }
}