using InvoiceManagementApi.Models;
using InvoiceManagementApi.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;

namespace InvoiceManagementApi.Controllers
{
    [Route("api/[controller]/[Action]")]
    [ApiController]
    [Authorize]
    public class InvoiceController : BaseController
    {
        private readonly ILogger<InvoiceController> _logger;
        private readonly IInvoiceRepository _invoiceRepository;

        public InvoiceController(ILogger<InvoiceController> logger, IInvoiceRepository invoiceRepository)
        {
            _logger = logger;
            _invoiceRepository = invoiceRepository;
        }

        [HttpGet]
        public async Task<IActionResult> GetInvoiceList([FromQuery] string? invoiceNum = null,[FromQuery] string? fromDate = null,[FromQuery] string? toDate = null)
        {
            try
            {
                var data = await _invoiceRepository.GetInvoiceAsync(invoiceNum, fromDate, toDate, CurrentUserId);

                // Project the dynamic objects to properly parse the SQL JSON string into an actual JSON object
                var formattedData = data.Select(row =>
                {
                    // Dapper dynamic rows act like a dictionary
                    var rowDict = (IDictionary<string, object>)row;

                    // Extract the raw JSON string generated by SQL's FOR JSON PATH
                    string? jsonDetails = rowDict.ContainsKey("JsonInvoiceDetails")
                        ? rowDict["JsonInvoiceDetails"]?.ToString()
                        : null;

                    // Parse it back to an object/element so ASP.NET serializes it properly instead of escaping quotes
                    rowDict["JsonInvoiceDetails"] = !string.IsNullOrEmpty(jsonDetails)
                        ? JsonSerializer.Deserialize<JsonElement>(jsonDetails)
                        : null;

                    return rowDict;
                });

                return Ok(formattedData);
            }
            catch (System.Exception ex)
            {
                _logger.LogError(ex, "Error getting Invoice List");
                return StatusCode(500, new { Message = "An error occurred" });
            }
        }

        /// <summary>
        /// Accepts an Invoice payload, performs basic validation and computes line/totals.
        /// Persists invoice via IInvoiceRepository.
        /// </summary>
        [HttpPost]
        public async Task<IActionResult> AddInvoice([FromBody] Invoice invoice)
        {
            if (invoice == null)
                return BadRequest(new { Message = "Invoice is required." });

            if (invoice.Items == null || !invoice.Items.Any())
                return BadRequest(new { Message = "Invoice must contain at least one item." });

            try
            {
                
                // Persist invoice using repository
                var repoResult = await _invoiceRepository.InsertOrUpdateInvoiceAsync(invoice, CurrentUserId);

                _logger.LogInformation("Invoice {InvoiceId} saved by user {UserId}. SubTotal={SubTotal}, GrandTotal={GrandTotal}",
                    invoice.Id, CurrentUserId?.ToString() ?? "anonymous", invoice.SubTotal, invoice.GrandTotal);

                return Ok(new
                {
                    Message = "Invoice processed and saved successfully.",
                    Invoice = invoice,
                    Result = repoResult
                });
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error processing invoice");
                return StatusCode(500, new { Message = "An error occurred while processing the invoice." });
            }
        }
    }
}